const TYPES = {
    SlackIncomingUrl: Symbol.for("SlackIncomingUrl"),
    SlackBotUserToken: Symbol.for("BotUserToken"),
    SlackVerificationToken: Symbol.for("SlackVerificationToken"),
    Container: Symbol.for("Container"),
    ScriptProperties: Symbol.for("ScriptProperties"),
    Configure: Symbol.for("Configure"),
    Spreadsheet: Symbol.for("Spreadsheet"),
    Sheets: Symbol.for("Sheets"),
    UserResolver: Symbol.for("UserResolver"),
    UsernameConverter: Symbol.for("UsernameConverter"),
    Message: Symbol.for("Message"),
    I18nFactory: Symbol.for("I18nFactory"),
    RequestFactory: Symbol.for("RequestFactory"),
    ResponseHandler: Symbol.for("ResponseHandler"),
    CommandRegistry: Symbol.for("CommandRegistry"),
    CommandResolver: Symbol.for("CommandResolver"),
    CommandDayTotal: Symbol.for("CommandDayTotal"),
    CommandSignIn: Symbol.for("CommandSignIn"),
    CommandSignOut: Symbol.for("CommandSignOut"),
    CommandNoRest: Symbol.for("CommandNoRest"),
    CommandRestHours: Symbol.for("CommandRestHours"),
    workedHoursCalculator: Symbol.for("workedHoursCalculator"),
    overtimeHoursCalculator: Symbol.for("overtimeHoursCalculator"),
    midnightHoursCalculator: Symbol.for("midnightHoursCalculator"),
    Calculator: Symbol.for("Calculator"),
}

export {TYPES};
